# Generated by Django 5.0.1 on 2024-01-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=120)),
                ('Position', models.CharField(max_length=120)),
                ('Department', models.CharField(max_length=120)),
                ('Pay', models.FloatField()),
                ('Grade', models.FloatField()),
                ('badges', models.URLField()),
            ],
        ),
    ]
