# Generated by Django 5.0.1 on 2024-01-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='badges',
            new_name='Badges',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='emp_id',
            new_name='Emp_id',
        ),
    ]
