# Generated by Django 5.0.1 on 2024-01-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_rename_badges_user_badges_rename_emp_id_user_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.CharField(default='root', max_length=120),
        ),
    ]
