# Generated by Django 5.0.1 on 2024-01-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Badges',
        ),
    ]
